### ISSUE TITLE
Saada data provider

### ISSUE THREAD

**Issue by lmichel** [lmichel/alix#10]
Les mises à jour trop fréquentes du champs de vue, molette souris p.e., faont que Saada retourne des fichiers inconsistants.  La raison en est certainement une collision des les noms de fichiers

**Comment by lmichel** [comment]
l'erreur se produit à (aladin.js:7778). Peut on essayer de catcher cette erreur?

**Comment by lmichel** [comment]
On peut aussi essayer de mettre un timeout sur le message "fetching..."

**Comment by XinyuSHAN** [comment]
Oui.Je suis totalement d'accord avec toi.
Aujourd'hui j'ai rencontré un bug similaire. C'est quand je clique "return center", il arrive la meme erreur.
![capture du 2018-11-14 17-20-15](https://user-images.githubusercontent.com/44768047/48498064-ae4d1c80-e835-11e8-837f-b9172b494984.png)
Et après j'ai trouvé que dans le fonction returnCenter() ,  gotoObject(defaultPosition)  demande les fichiers de saada. En plus aladin.setFoV() ont demander encore une fois.Il arrive le collision.
```javascript
var returnCenter = function(){
        //aladin.gotoObject(defaultPosition);
        gotoObject(defaultPosition);
        aladin.setFoV(defaultFov);
        aladin.gotoPosition(aladinLiteView.ra,aladinLiteView.dec);
        controller.cleanPolygon();
        //event.stopPropagation();
    }
```
Et j'enlève le aladin.setFoV(defaultFov) dedans , il y a plus l'erreur.
