### ISSUE TITLE
Paramètres distincts pour la largeur et pour la hauteur de la fenêtre d'AL

### ISSUE THREAD

**Issue by lmichel** [lmichel/alix#11]
Tous les éléments graphiques restent à la bonne place avec cette nouvelle configuration.
Le mode _rectangulaire_ remplace le mode _carré_ actuel.

**Comment by XinyuSHAN** [comment]
Ce mode peut etre testé avec la page 'testAlixRectangle.html'

**Comment by lmichel** [comment]
Apparemment ca marche, mais il faut que tu documentes la manière dont la fenêre Aladin est paramétrée.
Cela est nécesaire pour que je puisse tester
