### ISSUE TITLE
Test du mode rectangulaire

### ISSUE THREAD

**Issue by lmichel** [lmichel/alix#12]
Toutes les fonctions sont testées en mode _rectangulaire_
- Fonctions graphiques
- Fonctions le l'API
La liste des fonctionalités testées est reportée dans la présente issue.

**Comment by XinyuSHAN** [comment]
Le taille de snapshot est toujours carré ici. (Il a compressé l'img à une image carré). Mais dans la prochaine étape: la reorganisation de paramètres, je le corrigerais avec les autres paramètres.
