### ISSUE TITLE
Déclaration de la taille de la fenêtre d'ALIX en % de la vue courante.

### ISSUE THREAD

**Issue by lmichel** [lmichel/alix#13]
La taille de la vue est actuellement donnée en valeurs absolues (pixels). 
Cela peut poser problème lorsque l'application tourne sur un écran autre que celui utilisé pour le développement, ou lorsque l'on utilise un projecteur HD (p.e. macbook-pro + HDMI)
La fonction d'inititialisation doit supporter une définition de la taille en % de la vue.
Ce mode vient en supplément du mode actuel par une réorganisation des paramètres de la fonction _init_

**Comment by XinyuSHAN** [comment]
Coucou Laurent. Ce mode peut etre testé avec la page 'testAlixRelative.html' .
Mais j'ai pas encore fini la réorganisation des paramètres de la fonction init pour s'adapter. Du coup, il y a des bugs ,par exemple: la taille d'interface d'attends etc. Je le finirais bientôt. Et j'aimerais bien mettre en avance l'organisation des panneaux , parce que je trouve que ça concerne la réorganisation des paramètres.

**Comment by lmichel** [comment]
Apparemment ca marche, mais il faut que tu documentes la manière dont la fenêre Aladin est paramétrée.
Cela est nécesaire pour que je puisse tester

**Comment by lmichel** [comment]
L'important est que la configuration par valeurs relatives fonctionne et que tu me dises comment on la paramètre.
Dans tous las cas il faudra que puisses déduire la taille de tes panneaux de celle  d'AL, quitte à imposer des limites à cette dernière. 
La gestion de la taille des panneaux ne fait pas partie de ce jalon.
