### ISSUE TITLE
Définition des interaction entre les panneaux

### ISSUE THREAD

**Issue by lmichel** [lmichel/alix#15]
Definition de la localisation des différents panneaux sur la vue d'ALadinLite
Définitions des conditions d'ouvertue et de fermeture de chacun des panneaux
Les propositions seront mises sur une page dédiée du Wiki sous la forme de texte et de schémas, même faits à main levée

**Comment by XinyuSHAN** [comment]
https://github.com/lmichel/alix/wiki/Proposition-d'organisation-des-tableux
Coucou ! Excuse-moi pour ce retard. 🙁️
