### ISSUE TITLE
Progressive mode

### ISSUE THREAD

**Issue by lmichel** [lmichel/alix#2]
The progressive mode is not well supported for Vizize catalogues when we span the view

**Comment by XinyuSHAN** [comment]
Yes. I find it's because in the function updateCatalog(), the vizier catalogs progressive  didn't take the right url from the LibraryCatalog. And it's made over now.

**Comment by XinyuSHAN** [comment]
Et le problème de recentrage est réglé .
Dans le returnCenter() , il y avait aladin.gotoObject(defaultPosition), mais il faut le gotoObject(defaultPosition) qui va appeler "controller.updateCatalogs(aladinLiteView,'position')".
