### ISSUE TITLE
gestion des bookmarks

### ISSUE THREAD

**Issue by lmichel** [lmichel/alix#31]
Quand on clique  sur le coeur, le bookmark est enregistré et le panneau de gestion des bookmarks s'ouvre. La réaction normale des utilisateurs sera ensuite de réappuyer sur le coeur pour voir les bookmarks, ce qui provoquera l'enregistrement d'un nouveau bookmark etc.
Ce qu'il faudrait, c'est ouvrir une popup disant qu'un nouveau bookmark a été enregistré et qu'il peut être consulté en cliquant sur le bouton jaune. Cette popup modale devrait avoir son propre bouton de fermeture

**Comment by XinyuSHAN** [comment]
C'est réglé. Popup j'ai utilisé le plus simple 'alerte()', ça marche? 
![image](https://user-images.githubusercontent.com/44768047/59231226-3c2c9280-8be0-11e9-8bbf-da127b7bfb62.png)
Il y a les mots chinois c'est parce que chez moi c'est le navigateur chinois, mais ça dérange pas l'affichage chez vous :=)
