### ISSUE TITLE
Fenêtre de selection des HIPS: largeur

### ISSUE THREAD

**Issue by lmichel** [lmichel/alix#36]
Cette fenêtre semble déborder sur la droite. Il faut limiter sa largeur.

**Comment by XinyuSHAN** [comment]
Est-ce que c'est mieux comme ça?
<img width="1272" alt="图片" src="https://user-images.githubusercontent.com/44768047/59047622-84684f80-8884-11e9-95d7-70ef5bb7aea0.png">
Ou cacher quand-meme le bouton zoom?
<img width="1271" alt="图片" src="https://user-images.githubusercontent.com/44768047/59047715-a6fa6880-8884-11e9-817e-1afcd37a203a.png">
