### ISSUE TITLE
Affichage des READMES

### ISSUE THREAD

**Issue by lmichel** [lmichel/alix#38]
Ja'i déjà posté cet issue, mais je ne la vois plus.
Les readmes Vizier devraient s'afficher dans une fenêtre similaire à celle de sélection des HIPS
L'affichage actuel n'est pas visible.

**Comment by XinyuSHAN** [comment]
![image](https://user-images.githubusercontent.com/44768047/59230594-3635b200-8bde-11e9-9e9f-7896120154a3.png)
ça marche?
